// <auto-generated />

use super::ClientOperation;
use opentelemetry::trace::SpanKind;

pub(crate) const DB_COLLECTION_NAME: &str = "db.collection.name";
pub(crate) const DB_OPERATION_NAME: &str = "db.operation.name";
pub(crate) const DB_SYSTEM_NAME: &str = "db.system.name";
pub(crate) const ERROR_TYPE: &str = "error.type";
pub(crate) const MESSAGING_CONSUMER_GROUP_NAME: &str = "messaging.consumer.group.name";
pub(crate) const MESSAGING_DESTINATION_NAME: &str = "messaging.destination.name";
pub(crate) const MESSAGING_MESSAGE_ID: &str = "messaging.message.id";
pub(crate) const MESSAGING_OPERATION_NAME: &str = "messaging.operation.name";
pub(crate) const MESSAGING_OPERATION_TYPE: &str = "messaging.operation.type";
pub(crate) const MESSAGING_SYSTEM: &str = "messaging.system";
pub(crate) const TROGON_EVENTSTORE_BATCH_CORRELATION_ID: &str =
    "trogon.eventstore.batch.correlation_id";
pub(crate) const TROGON_EVENTSTORE_EVENT_TYPE: &str = "trogon.eventstore.event.type";

pub(crate) const CLIENT_SPAN_KIND: SpanKind = SpanKind::Client;
pub(crate) const RECEIVE_SPAN_KIND: SpanKind = SpanKind::Client;

pub(crate) mod operation {
    use super::ClientOperation;

    pub(crate) const APPEND_TO_STREAM: ClientOperation = ClientOperation::new("append_to_stream");
    pub(crate) const BATCH_APPEND: ClientOperation = ClientOperation::new("batch_append");
    pub(crate) const BATCH_APPEND_TO_STREAM: ClientOperation =
        ClientOperation::new("batch_append_to_stream");
    pub(crate) const CREATE_PERSISTENT_SUBSCRIPTION: ClientOperation =
        ClientOperation::new("create_persistent_subscription");
    pub(crate) const CREATE_PERSISTENT_SUBSCRIPTION_TO_ALL: ClientOperation =
        ClientOperation::new("create_persistent_subscription_to_all");
    pub(crate) const DELETE_PERSISTENT_SUBSCRIPTION: ClientOperation =
        ClientOperation::new("delete_persistent_subscription");
    pub(crate) const DELETE_PERSISTENT_SUBSCRIPTION_TO_ALL: ClientOperation =
        ClientOperation::new("delete_persistent_subscription_to_all");
    pub(crate) const DELETE_STREAM: ClientOperation = ClientOperation::new("delete_stream");
    pub(crate) const GET_PERSISTENT_SUBSCRIPTION_INFO: ClientOperation =
        ClientOperation::new("get_persistent_subscription_info");
    pub(crate) const GET_PERSISTENT_SUBSCRIPTION_INFO_TO_ALL: ClientOperation =
        ClientOperation::new("get_persistent_subscription_info_to_all");
    pub(crate) const GET_STREAM_METADATA: ClientOperation =
        ClientOperation::new("get_stream_metadata");
    pub(crate) const LIST_ALL_PERSISTENT_SUBSCRIPTIONS: ClientOperation =
        ClientOperation::new("list_all_persistent_subscriptions");
    pub(crate) const LIST_PERSISTENT_SUBSCRIPTIONS_FOR_STREAM: ClientOperation =
        ClientOperation::new("list_persistent_subscriptions_for_stream");
    pub(crate) const LIST_PERSISTENT_SUBSCRIPTIONS_TO_ALL: ClientOperation =
        ClientOperation::new("list_persistent_subscriptions_to_all");
    pub(crate) const READ_ALL: ClientOperation = ClientOperation::new("read_all");
    pub(crate) const READ_STREAM: ClientOperation = ClientOperation::new("read_stream");
    pub(crate) const REPLAY_PARKED_MESSAGES: ClientOperation =
        ClientOperation::new("replay_parked_messages");
    pub(crate) const REPLAY_PARKED_MESSAGES_TO_ALL: ClientOperation =
        ClientOperation::new("replay_parked_messages_to_all");
    pub(crate) const RESTART_PERSISTENT_SUBSCRIPTION_SUBSYSTEM: ClientOperation =
        ClientOperation::new("restart_persistent_subscription_subsystem");
    pub(crate) const SET_STREAM_METADATA: ClientOperation =
        ClientOperation::new("set_stream_metadata");
    pub(crate) const SUBSCRIBE_TO_ALL: ClientOperation = ClientOperation::new("subscribe_to_all");
    pub(crate) const SUBSCRIBE_TO_PERSISTENT_SUBSCRIPTION: ClientOperation =
        ClientOperation::new("subscribe_to_persistent_subscription");
    pub(crate) const SUBSCRIBE_TO_PERSISTENT_SUBSCRIPTION_TO_ALL: ClientOperation =
        ClientOperation::new("subscribe_to_persistent_subscription_to_all");
    pub(crate) const SUBSCRIBE_TO_STREAM: ClientOperation =
        ClientOperation::new("subscribe_to_stream");
    pub(crate) const TOMBSTONE_STREAM: ClientOperation = ClientOperation::new("tombstone_stream");
    pub(crate) const UPDATE_PERSISTENT_SUBSCRIPTION: ClientOperation =
        ClientOperation::new("update_persistent_subscription");
    pub(crate) const UPDATE_PERSISTENT_SUBSCRIPTION_TO_ALL: ClientOperation =
        ClientOperation::new("update_persistent_subscription_to_all");
}
